PROJECT_NAME: "ot_swirly"                 # Name of the project
TRAIN_NAME: "ot_swirly_conv3x3"              # Name of the training run
SEED: 42                                  # Random seed
DEVICE: "cuda"                             # Device to use for training
WANDB: true                               # Flag to enable logging to Weights & Biases

MODEL:
  NAME: "MLP"
  HIDDEN_CHANNELS: [128]
  CHANNEL_N: 24
  USE_POSITIONAL_EMBEDDINGS: False
  LIVING_MASK: false
  NORMALIZE_OUTPUT: false
  FINAL_ACTIVATION: false
  PERCEPTIONS:
    - MODE: "conv"
      KERNEL_SIZE: 3
      OUT_CHANNEL: 128


TRAINING:
  BATCH_SIZE: 12
  STEPS: 50000
  LEARNING_RATE: 0.002
  LR_SCHEDULE_MODE: "cosine"
  LOSS_FN: "vgg"
  WARMUP_STEPS: 2500
  OVERFLOW_LOSS: true
  GAMMA: 0.1
  LOG_INTERVAL: 500
  SAVE_INTERVAL: 25000
  ITER_N_MIN: 12
  ITER_N_MAX: 22
  INTERMEDIATE_LOGGING_STEPS: [5, 10]
  GRADIENT_CLIPPING_NORM: 1.0
  GRADIENT_CHECKPOINTING: false
  GRADIENT_CHECKPOINT_SEGMENTS: 10
  GRADIENT_ACCUMULATION_STEPS: 1

DATASET:
  NAME: "ot"                            # Name of the dataset [emoji, e2h, mnist]
  DATASET_SAMPLE_PATH: "./train_log/ot_swirly_conv3x3/swirly_0066.jpg"
  TARGET_SIZE: 168

PATTERN_POOL:
  ENABLED: true
  POOL_SIZE: 1024
  POOL_DELAY: 1
  POOL_START_RATIO: 0.5
  POOL_END_RATIO: 0.5
  POOL_DMG_RATIO: 0.5
  POOL_DMG_DELAY: 1
  POOL_MUTATION_RATIO: 0.5