PROJECT_NAME: "mnist"                 # Name of the project
TRAIN_NAME: "mnist_mse"              # Name of the training run
SEED: 42                                  # Random seed
DEVICE: "cuda"                             # Device to use for training
WANDB: true                               # Flag to enable logging to Weights & Biases

MODEL:
  NAME: "ConvCA"
  HIDDEN_CHANNELS: [80]
  CHANNEL_N: 20
  CHANNEL_OUT: 19
  USE_POSITIONAL_EMBEDDINGS: False
  LIVING_MASK: true
  LIVING_MASK_INDEX: 0
  CLAMP_OUTPUT: false
  FINAL_ACTIVATION: false
  PERCEPTIONS:
    - MODE: "conv"
      KERNEL_SIZE: 3
      OUT_CHANNEL: 80


TRAINING:
  BATCH_SIZE: 18
  STEPS: 100000
  LEARNING_RATE: 0.002
  LR_SCHEDULE_MODE: "cosine"
  LOSS_FN: "mse"
  WARMUP_STEPS: 5000
  OVERFLOW_LOSS: true
  GAMMA: 0.1
  LOG_INTERVAL: 500
  SAVE_INTERVAL: 25000
  ITER_N_MIN: 20
  ITER_N_MAX: 30
  INTERMEDIATE_LOGGING_STEPS: [5, 10, 15]
  GRADIENT_CLIPPING_NORM: 1.0
  GRADIENT_CHECKPOINTING: false
  GRADIENT_CHECKPOINT_SEGMENTS: 10
  GRADIENT_ACCUMULATION_STEPS: 1

DATASET:
  NAME: "mnist"                            # Name of the dataset [emoji, e2h, mnist]
  TARGET_PADDING: 12
  DATAROOT: "datasets/mnist"

PATTERN_POOL:
  ENABLED: true
  POOL_SIZE: 1024
  POOL_DELAY: 1
  POOL_DMG_DELAY: 1
  POOL_START_RATIO: 0.5
  POOL_END_RATIO: 0.5
  POOL_DMG_RATIO: 0.0
  POOL_MUTATION_RATIO: 1.0
